# Generated by Django 4.1.2 on 2022-12-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='URL',
            new_name='url',
        ),
    ]
