# Generated by Django 4.1.2 on 2022-12-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_rename_url_show_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='endyear',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
