# Generated by Django 4.1.2 on 2022-12-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0003_alter_show_endyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='premiered',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
