# Generated by Django 4.1.2 on 2022-12-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0004_show_premiered'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
