# Generated by Django 4.1.2 on 2022-12-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0005_show_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='show',
            name='endyear',
        ),
        migrations.RemoveField(
            model_name='show',
            name='image',
        ),
        migrations.RemoveField(
            model_name='show',
            name='mostrecentairdate',
        ),
        migrations.RemoveField(
            model_name='show',
            name='premiered',
        ),
        migrations.RemoveField(
            model_name='show',
            name='startyear',
        ),
        migrations.RemoveField(
            model_name='show',
            name='status',
        ),
        migrations.RemoveField(
            model_name='show',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='show',
            name='trackers',
        ),
        migrations.RemoveField(
            model_name='show',
            name='url',
        ),
        migrations.AddField(
            model_name='user',
            name='shows',
            field=models.ManyToManyField(blank=True, related_name='trackers', to='tv.show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
